name: docker-postgres

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pull-install-lint

    steps:
      - uses: actions/checkout@v4

      - name: Start PostgreSQL
        run: |
          docker run -d \
            --name postgres \
            --env POSTGRES_USER=postgres \
            --env POSTGRES_PASSWORD=postgres \
            --env POSTGRES_DB=postgres \
            --publish 5432:5432 \
            --health-cmd pg_isready \
            --health-interval 10s \
            --health-timeout 5s \
            --health-retries 5 \
            postgres:15 \
            -c max_locks_per_transaction=1024 
          
