# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pull-install-lint

    strategy:
      matrix:
        node-version: [18.x] #[14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./pull-install-lint/package-lock.json

      - run: npm ci

      # - run: npm run build --if-present # dont want to build right now
      # - run: npm test # dont want to run tests right now

      # - name: Run Linter
      #   run: npx eslint . --ext .js,.ts

      - name: cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./pull-install-lint
          start: npm start
          wait-on: http://[::1]:4200
          
